### ISSUE TITLE
อ่านบัตรของปี 2559 ไม่ได้

### ISSUE THREAD

**Issue by panyachainu** [chakphanu/ThaiNationalIDCard#2]
เวลาเสียบบัตร แล้วมันอ่านไม่ได้ของปี 2559 คืนค่า null กลับมาครับ
ไม่ทราบว่า ตัวบัตรมีการเปลี่ยนแปลงอะไรหรือป่าวครับ บัตร 2559 ส่วนใหญ่อ่านไม่ได้เลยครับ

**Comment by chakphanu** [comment]
update lib/dll ดูครับ

เมื่อ 29 ก.ย. 2016 16:53 "panyachainu" <notifications@github.com> เขียนว่า

**Comment by panyachainu** [comment]
@chakphanu : อัพเดทแล้วนะครับ เป็น Version 1.0.2 บน Github เลยครับ

**Comment by chakphanu** [comment]
@panyachainu ตอนรันลองดูตรง console/debug window ว่ามี debug message ขึ้นอะไรเป็นพิเศษไหมครับ

**Comment by panyachainu** [comment]
พอดีผมใช้ Function
ThaiNation.ThaiIDCard idcard = new ThaiNation.ThaiIDCard();
ThaiNation.Personal personal = idcard.readAllPhoto();

แล้วมันขึ้น Error ตามภาพด้านล่างนี้ ไม่ทราบว่าเป็นที่ บัตรประชาชนหรือว่าอะไรหรอครับ ไม่เป็นทุกบัตรนะครับ

![p1](https://cloud.githubusercontent.com/assets/12842072/19756925/0cb0c824-9c4a-11e6-92ab-e2a33674e1cc.PNG)

![p2](https://cloud.githubusercontent.com/assets/12842072/19756926/0cbb0f14-9c4a-11e6-9ece-630b0429587c.PNG)

**Comment by chakphanu** [comment]
มี app หรือ process อื่น lock เครื่องอ่านบัตรไว้อยู่

เมื่อ 27 ต.ค. 2016 13:37 "panyachainu" <notifications@github.com> เขียนว่า

พอดีผมใช้ Function
ThaiNation.ThaiIDCard idcard = new ThaiNation.ThaiIDCard();
ThaiNation.Personal personal = idcard.readAllPhoto();

แล้วมันขึ้น Error ตามภาพด้านล่างนี้ ไม่ทราบว่าเป็นที่
บัตรประชาชนหรือว่าอะไรหรอครับ ไม่เป็นทุกบัตรนะครับ

[image: p1]
<https://cloud.githubusercontent.com/assets/12842072/19756925/0cb0c824-9c4a-11e6-92ab-e2a33674e1cc.PNG>

[image: p2]
<https://cloud.githubusercontent.com/assets/12842072/19756926/0cbb0f14-9c4a-11e6-9ece-630b0429587c.PNG>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/chakphanu/ThaiNationalIDCard/issues/2#issuecomment-256558940>,
or mute the thread

**Comment by panyachainu** [comment]
@chakphanu : แล้วพอมีวิธีไหนบ้างที่ คลิกปุ่ม แล้วเหมือนเราสั่ง Even CardInsert บ้างครับ 
(เสมือนเราถอดบัตรแล้วเสียบใหม่)
กรณี Error ข้างบน ผมสั่งให้อ่านซ้ำรอบ 2 โดยรอบแรกอ่านตอนเสียบบัตร จะเข้า Even CardInsert 
และรอบ 2 สั่ง Fuction readAllPhoto()

ขอบคุณมากๆๆ ครับ

**Comment by chakphanu** [comment]
ลองแก้ thai idcard lib  จาก SCardShareMode.Exclusive เป็น SCardShareMode.Shared ดูครับ
ถ้าได้ผล ผมจะได้ update lib อีกที

**Comment by panyachainu** [comment]
@chakphanu : แก้เป็น SCardShareMode.Shared แล้วไม่ขึ้น Error ครับ ทำงานได้ปกติ
ในการสั่งจาก Function readAllPhoto()

**Comment by agekop** [comment]
ใช้กับเครื่องอ่านบัตรรุ่นไหนได้บ้างครับ
ช่วยแนะนำหน่อยครับ  
ขอบคุณครับ

**Comment by ibee133** [comment]
ค่าศาสนา มีให้อ่านไหมครับ ลองแล้วไม่เจอครับ

**Comment by prakasitlasree** [comment]
เจอ issue นี้เหมือนกันครับ ทั้งปี 59 กับ 60 เลย

update lib/dll ดูครับ  ให้เอา dll มาจากไหนครับ
